# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
		  . ~/.bashrc
fi

# User specific environment and startup programs
OS=`uname -s`

PATH=$PATH:$HOME/bin
export GOPATH=$HOME/go
if [ $OS == "Darwin" ];
    then
    PATH=$PATH:/opt/metasploit-framework/bin
fi
export PATH
