# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
		  . ~/.bashrc
fi

# User specific environment and startup programs
OS=`uname -s`

PATH=$PATH:$HOME/bin
export GOPATH=$HOME/go
PATH=$PATH:$HOME/bin:$GOPATH/bin
if [ $OS == "Darwin" ];
    then
    PATH=$PATH:/opt/metasploit-framework/bin
    PATH=/usr/local/opt/openssl@1.1/bin:$PATH
fi
export PATH
